/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ATree: typeof import('ant-design-vue/es')['Tree']
    Avatar: typeof import('./components/base/Avatar/avatar.vue')['default']
    Calendar: typeof import('./components/base/Calendar/calendar.vue')['default']
    EChartsUI: typeof import('./components/base/EChartsUI/index.vue')['default']
    Modal: typeof import('./components/base/Modal/modal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TMap: typeof import('./components/base/TMap/index.vue')['default']
  }
}
