/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export { }

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ATree: typeof import('ant-design-vue/es')['Tree']
    Avatar: typeof import('./shared/components/base/Avatar/src/avatar.vue')['default']
    Calendar: typeof import('./shared/components/base/Calendar/src/calendar.vue')['default']
    EChartsUI: typeof import('./shared/components/base/EChartsUI/src/echarts-ui.vue')['default']
    Modal: typeof import('./shared/components/base/Modal/src/modal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TMap: typeof import('./shared/components/base/TMap')['default']
  }
}
