name: Deploy to GitHub Pages
# 触发条件
on:
  push:
    branches:
      # 推送到主分支时触发
      - main
  # 手动触发
  workflow_dispatch:

# 设置GITHUB_TOKEN的权限
permissions:
  contents: write
  pages: write
  id-token: write

# 允许一个并发部署
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  # 构建任务
  build:
    # 运行在 ubuntu 最新版本
    runs-on: ubuntu-latest
    # 环境变量
    env:
      # 项目标题
      IHRM_APP_TITLE: '企业级人力资源管理系统'
      # 项目 API 基础 URL
      IHRM_APP_API_BASE_URL: 'https://heimahr.itheima.net'
      # 项目基础 URL
      IHRM_BASE_URL: '/saas-hrm/'
      # 项目描述
      IHRM_APP_DESCRIPTION: '企业级人力资源管理系统'
      IHRM_ASSETS_URL: '/saas-hrm/'

      
    # 步骤
    steps:
      # 检查代码
      - name: Checkout
        uses: actions/checkout@v4
      
      # 设置 Node 版本
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      
      # 安装依赖并构建
      - name: Install Dependencies and Build
        run: | 
          npm install
          npm run build-only
      
      # 部署到 GitHub Pages
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with: 
          folder: dist
   